[package]
name = "gimlet-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
tempfile = "3.20.0"
which = "8.0.0"

[[bin]]
name = "gimlet-cli"
path = "src/main.rs"